#!/usr/bin/env python3
"""Generate docs/projects/INDEX.md — an auto-index of all projects.

Categories are simply the directories you create under docs/projects/ — they are
detected automatically, no hardcoded taxonomy. Reads each project's SUMMARY.md
(fallback README.md), extracts title / Status / Last updated, and emits one table
per category plus an anti-drift "Gaps" section listing folders that lack a SUMMARY
or a Status line. Idempotent: writes only when content changes. Always exits 0
(the pre-commit hook warns, never blocks).

Layout detection (deterministic):
  - `_archive` is always treated as a category (its README.md is a convention doc,
    not a project) and is listed last.
  - a directory that itself contains SUMMARY.md or README.md is a flat project
    (listed under "Uncategorized") — this keeps a flat docs/projects/ working.
  - any other directory is a category; its subdirectories are its projects.

Convention (same bold-line format tools/brain/build.py parses — deliberately NO
YAML frontmatter, to avoid a second source of drift):
    # Title
    **Status:** <status>      (or  **Status: <status>**)
    **Last updated:** <date>
"""
import re, pathlib, sys

ROOT = pathlib.Path(__file__).resolve().parents[2]

TITLE_RE = re.compile(r"^#\s+(.+?)\s*$", re.M)
STATUS_RES = [
    re.compile(r"^\*\*Status:\*\*\s*(.+?)\s*$", re.M),   # **Status:** value
    re.compile(r"^\*\*Status:\s*(.+?)\*\*", re.M),       # **Status: value** (value inside bold, text may follow)
    re.compile(r"^Status:\s*(.+?)\s*$", re.M),           # Status: value
]
UPDATED_RES = [
    re.compile(r"^\*\*Last updated:\*\*\s*(.+?)\s*$", re.M),
    re.compile(r"^\*\*Last updated:\s*(.+?)\*\*\s*$", re.M),
]


def clean(s):
    """Trim a status/date to a compact, single-line, table-safe form."""
    s = s.replace("|", "\\|").strip()
    s = re.sub(r"`([^`]*)`", r"\1", s)          # drop code ticks
    s = re.sub(r"\*\*([^*]*)\*\*", r"\1", s)    # drop bold
    # first clause only
    for sep in [" — ", ". ", "; "]:
        if sep in s:
            s = s.split(sep)[0]
            break
    if len(s) > 90:
        s = s[:87].rstrip() + "…"
    return s


def first(res, text):
    for r in res:
        m = r.search(text)
        if m:
            return m.group(1)
    return None


def is_project(d):
    return (d / "SUMMARY.md").is_file() or (d / "README.md").is_file()


def detect_sections(projects_dir):
    """Return an ordered list of (section_name, [project_dirs]).

    Order: regular categories (case-insensitive) -> "Uncategorized" (flat projects,
    if any) -> "_archive" (always last).
    """
    dirs = sorted(
        [d for d in projects_dir.iterdir() if d.is_dir() and not d.name.startswith(".")],
        key=lambda d: d.name.lower(),
    )
    categories, flat, archive = [], [], None
    for d in dirs:
        if d.name == "_archive":
            subs = sorted([s for s in d.iterdir() if s.is_dir()], key=lambda s: s.name.lower())
            archive = ("_archive", subs)
        elif is_project(d):
            flat.append(d)
        else:
            subs = sorted([s for s in d.iterdir() if s.is_dir()], key=lambda s: s.name.lower())
            categories.append((d.name, subs))
    sections = list(categories)
    if flat:
        sections.append(("Uncategorized", flat))
    if archive is not None:
        sections.append(archive)
    return sections


def main():
    root = ROOT
    if "--root" in sys.argv:
        root = pathlib.Path(sys.argv[sys.argv.index("--root") + 1]).resolve()
    projects_dir = root / "docs" / "projects"

    lines = [
        "<!-- AUTO-GENERATED by tools/projects_index/build.py — do NOT edit by hand.",
        "     Source: the **Status:** / **Last updated:** lines in each project's SUMMARY.md. -->",
        "",
        "# Projects — INDEX",
        "",
        "Full list of all projects by category. Categories are simply the directories you",
        "create under `docs/projects/` — the generator detects them automatically.",
        "",
    ]
    gaps = []
    sections = detect_sections(projects_dir) if projects_dir.is_dir() else []
    for name, projects in sections:
        flat = name == "Uncategorized"
        lines.append(f"## {name}")
        lines.append("")
        lines.append("| Project | Status | Last updated |")
        lines.append("|:--------|:-------|:-------------|")
        for proj in projects:
            gap_id = proj.name if flat else f"{name}/{proj.name}"
            summary = proj / "SUMMARY.md"
            src = summary if summary.exists() else (proj / "README.md")
            if not src.exists():
                gaps.append(f"`{gap_id}` — missing SUMMARY.md and README.md")
                lines.append(f"| `{proj.name}` | — (no SUMMARY/README) | — |")
                continue
            rel = src.relative_to(projects_dir).as_posix()
            text = src.read_text(encoding="utf-8", errors="replace")
            status = first(STATUS_RES, text)
            updated = first(UPDATED_RES, text) or "—"
            if status is None:
                gaps.append(f"`{gap_id}` — missing a **Status:** line in {src.name}")
                status_disp = "— (no **Status:**)"
            else:
                status_disp = clean(status)
            lines.append(f"| [{proj.name}]({rel}) | {status_disp} | {clean(updated)} |")
        lines.append("")

    lines.append("## Gaps (anti-drift)")
    lines.append("")
    if gaps:
        lines.append("Folders without a SUMMARY.md or a `**Status:**` line (fill these in to keep the INDEX complete):")
        lines.append("")
        for g in gaps:
            lines.append(f"- {g}")
    else:
        lines.append("None — every project has a SUMMARY/README with a Status line. ✅")
    lines.append("")

    out = projects_dir / "INDEX.md"
    new = "\n".join(lines)
    old = out.read_text(encoding="utf-8") if out.exists() else None
    if new != old:
        out.write_text(new, encoding="utf-8")
        print(f"projects INDEX.md: {len(sections)} categor(ies), {len(gaps)} gap(s) -> {out}")
    else:
        print("projects INDEX.md: up to date")


if __name__ == "__main__":
    main()
    sys.exit(0)
