#!/usr/bin/env python3
"""
Build LLM-generated summaries for video lessons using OpenAI.

Usage:
    python scripts/build_llm_summaries.py
    python scripts/build_llm_summaries.py --lesson 01_example_lesson
    python scripts/build_llm_summaries.py --dry-run
"""

import argparse
import json
import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# Load .env from project root
ROOT_DIR = Path(__file__).resolve().parents[3]  # <repo_root>
load_dotenv(ROOT_DIR / ".env")

CHUNKS_DIR = Path(__file__).parent.parent / "chunks"
SUMMARIES_DIR = Path(__file__).parent.parent / "summaries"

# OpenAI settings
MAX_CHUNKS_FOR_SUMMARY = 20  # Limit chunks to avoid token overflow
MAX_CHARS_PER_CHUNK = 2000   # Truncate long chunks
MODEL = "gpt-5.2-2025-12-11"


def get_openai_client():
    """Get OpenAI client."""
    from openai import OpenAI
    return OpenAI()


def read_chunks(lesson_id: str) -> list[dict]:
    """Read all chunks for a lesson."""
    chunk_file = CHUNKS_DIR / f"lesson_{lesson_id}.chunks.jsonl"
    if not chunk_file.exists():
        return []

    chunks = []
    with open(chunk_file, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                chunks.append(json.loads(line))
    return chunks


def build_prompt(chunks: list[dict], lesson_title: str) -> str:
    """Build prompt for LLM to generate summary."""
    # Take representative chunks (first, middle, last)
    if len(chunks) > MAX_CHUNKS_FOR_SUMMARY:
        step = len(chunks) // MAX_CHUNKS_FOR_SUMMARY
        selected = [chunks[i] for i in range(0, len(chunks), step)][:MAX_CHUNKS_FOR_SUMMARY]
    else:
        selected = chunks

    # Build transcript excerpt
    transcript_parts = []
    for i, chunk in enumerate(selected):
        text = chunk.get("text_clean") or chunk.get("text", "")
        if len(text) > MAX_CHARS_PER_CHUNK:
            text = text[:MAX_CHARS_PER_CHUNK] + "..."
        time_start = chunk.get("start_time_hms", "00:00:00")
        transcript_parts.append(f"[{time_start}] {text}")

    transcript = "\n\n".join(transcript_parts)

    prompt = f"""You are summarizing a video lesson from an educational course.

LESSON TITLE: {lesson_title}

TRANSCRIPT EXCERPTS:
{transcript}

---

Generate a summary with the following structure:

## Key Takeaways
- [3-5 bullet points of main insights]

## Topics Covered
- [List of main topics discussed]

## Actionable Tips
- [2-3 practical tips from the lesson]

## One-Sentence Summary
[Single sentence capturing the essence of the lesson]

Keep the summary concise but informative. Focus on practical, actionable knowledge."""

    return prompt


def generate_summary(client, prompt: str) -> str:
    """Generate summary using OpenAI."""
    response = client.chat.completions.create(
        model=MODEL,
        max_completion_tokens=1024,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )
    return response.choices[0].message.content


def save_summary(lesson_id: str, lesson_title: str, summary: str, chunk_count: int):
    """Save summary to markdown file."""
    SUMMARIES_DIR.mkdir(parents=True, exist_ok=True)

    output_path = SUMMARIES_DIR / f"lesson_{lesson_id}.summary.md"

    content = f"""# {lesson_title}

**Chunks analyzed:** {chunk_count}
**Generated by:** OpenAI {MODEL} (LLM)

---

{summary}
"""

    output_path.write_text(content, encoding="utf-8")
    print(f"  Saved: {output_path}")


def process_lesson(client, lesson_id: str, dry_run: bool = False) -> bool:
    """Process a single lesson. Returns True if processed."""
    chunks = read_chunks(lesson_id)
    if not chunks:
        print(f"  [SKIP] No chunks found for {lesson_id}")
        return False

    lesson_title = chunks[0].get("lesson_title", lesson_id)

    if dry_run:
        print(f"  [DRY-RUN] Would process {lesson_id}: {len(chunks)} chunks")
        return True

    print(f"  Processing {lesson_id}: {len(chunks)} chunks...")

    prompt = build_prompt(chunks, lesson_title)
    summary = generate_summary(client, prompt)
    save_summary(lesson_id, lesson_title, summary, len(chunks))

    return True


def main():
    parser = argparse.ArgumentParser(description="Build LLM summaries for video lessons")
    parser.add_argument("--lesson", default=None, help="Process specific lesson_id only")
    parser.add_argument("--dry-run", action="store_true", help="Preview without calling OpenAI")
    args = parser.parse_args()

    # Check API key
    if not args.dry_run and not os.environ.get("OPENAI_API_KEY"):
        print("ERROR: OPENAI_API_KEY not set in .env")
        sys.exit(1)

    client = None if args.dry_run else get_openai_client()

    # Find lessons to process
    if args.lesson:
        lessons = [args.lesson]
    else:
        chunk_files = sorted(CHUNKS_DIR.glob("lesson_*.chunks.jsonl"))
        lessons = [f.stem.replace("lesson_", "").replace(".chunks", "") for f in chunk_files]

    print(f"=== LLM Summary Generator (OpenAI {MODEL}) ===")
    print(f"  Lessons to process: {len(lessons)}")
    print(f"  Dry run: {args.dry_run}")
    print()

    processed = 0
    for lesson_id in lessons:
        if process_lesson(client, lesson_id, args.dry_run):
            processed += 1

    print(f"\nProcessed: {processed} lesson(s)")


if __name__ == "__main__":
    main()
